version: '3'
services:
  test:
    build: .
    command: 'npm run test:docker:ci'
    depends_on:
      - postgres
      - rediscluster
      - rabbitmq
    volumes:
      - .:/usr/windbreaker
      - /usr/windbreaker/node_modules
  postgres:
    image: 'postgres:9.6.3-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'windbreaker_service_util'
    ports:
      - '5432'
  rediscluster:
    image: 'grokzen/redis-cluster'
    ports:
      - "7000"
      - "7001"
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - '5672'
